services:
    postgres:
        image: postgres:16-alpine
        container_name: chatly-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: chatly
            POSTGRES_USER: chatly
            POSTGRES_PASSWORD: chatly123
        volumes:
            - chatly-postgres-data:/var/lib/postgresql/data

    mongodb:
        image: mongo:7
        container_name: chatly-mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: chatly
        volumes:
            - chatly-mongo-data:/data/db

    redis:
        image: redis:7-alpine
        container_name: chatly-redis
        ports:
            - "6379:6379"
        volumes:
            - chatly-redis-data:/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: chatly-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@chatly.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
            - chatly-pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres

    redisinsight:
        image: redis/redisinsight:latest
        container_name: chatly-redisinsight
        ports:
            - "5540:5540"
        depends_on:
            - redis

volumes:
    chatly-postgres-data:
    chatly-mongo-data:
    chatly-redis-data:
    chatly-pgadmin-data:
