package com.chatly.model.enums;

public enum SignalType {
    OFFER,
    ANSWER,
    ICE_CANDIDATE,
    INITIATE,
    END,
    VIDEO_UPGRADE_REQUEST,
    VIDEO_UPGRADE_ACCEPT,
    VIDEO_UPGRADE_REJECT,
    RENEGOTIATE_OFFER,
    RENEGOTIATE_ANSWER,
    GROUP_INITIATE,
    GROUP_JOIN,
    GROUP_OFFER,
    GROUP_ANSWER,
    GROUP_LEAVE,
    GROUP_VIDEO_UPGRADE_REQUEST,
    GROUP_VIDEO_UPGRADE_ACCEPT,
    GROUP_VIDEO_UPGRADE_REJECT,
    GROUP_RENEGOTIATE_OFFER,
    GROUP_RENEGOTIATE_ANSWER
}
