spring:
    application:
        name: chatly-backend

    datasource:
        url: jdbc:postgresql://localhost:5432/chatly
        username: chatly
        password: chatly123
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    sql:
        init:
            mode: never # chịu khó gọi Postman 'register / create' data sample đi seed lag vc:v
            data-locations: classpath:db/seed-data.sql

    data:
        mongodb:
            uri: mongodb://localhost:27017/chatly
        redis:
            host: localhost
            port: 6379

server:
    port: 8080

logging:
    level:
        org.springframework.web.socket: DEBUG
        org.springframework.messaging: DEBUG

app:
    jwt:
        secret: Y2hhdGx5LXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLTIwMjY=
        expiration-ms: 86400000 # 1d
        refresh-expiration-ms: 86400000 # 1d
    cors:
        allowed-origins: http://localhost:3000, http://localhost:5174
